# spring_params.yaml

#   spring_stiffness: K in Nm
#   spring_reference: Natural angle in deg 

right_linkj: # front joint
  spring_stiffness: 5.0       
  spring_reference: 30     

left_linkj: # middle joint
  spring_stiffness: 5.0
  spring_reference: 0

link3j: # rear joint
  spring_stiffness: 10.0
  spring_reference: 0

