# spring_params.yaml

#   spring_stiffness: K in Nm
#   spring_reference: Natural angle in deg 

right_linkj: # front joint
  spring_stiffness: 2.2       
  spring_reference: 90    

left_linkj: # middle joint
  spring_stiffness: 2.2
  spring_reference: 90

link3j: # rear joint
  spring_stiffness: 2.2
  spring_reference: 90

